spring:
  application:
    name: "spring_batch"

  batch:
    jdbc:
      initialize-schema: always

data01:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/data01
    username: root
    password: 123

data02:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/data02
    username: root
    password: 123