version: '3.8'

services:
  mysqlData:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root1
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=data01

  mysqlData02:
    image: mysql:latest
    ports:
      - 3307:3307
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root2
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=data02
