spring:
  application:
    name: "spring_batch"

  batch:
    jdbc:
      initialize-schema: always

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data01
    username: root
    password: 123


data02:
  batch:
    jdbc:
      initialize-schema: always

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/data02
    username: root
    password: 123